export const FETCH_APPOITMENTS_DATE = 'FETCH_APPOITMENTS_DATE';
export const FETCH_APPOITMENTS_TIME = 'FETCH_APPOITMENTS_TIME';
export const ADD_APPOITMENT = 'ADD_APPOITMENT';
export const ADD_APPOITMENT_TIME = 'ADD_APPOITMENT_TIME';
export const UPDATE_APPOITMENTS_TIME_BY_ID = 'UPDATE_APPOITMENTS_TIME_BY_ID';
export const DELETE_APPOITMENT_DATE = 'DELETE_APPOITMENT_DATE';
export const DELETE_APPOITMENT_TIME = 'DELETE_APPOITMENT_TIME';
export const APPOITMENTS_LOADING = 'APPOITMENTS_LOADING';